


clone:
  git:
    image: plugins/git
    depth: 50
    commands:
      - echo 'clone success'
      - echo ${DRONE_REPO_PRIVATE}
    when:
      branch: drone

pipeline:
  build:
    image: node:7.8
    privileged: true
    commands:
      - npm run build
      - echo 'build success'
    when:
      branch: [dev, wenke, lwz, yiletian, zhongzf, master, release, drone]


