workspace:
  base: /data/apps/opt
  path: web-im

clone:
  git:
    image: plugins/git
    volumes:
      - /data/apps/opt/web-im/${DRONE_BRANCH}:/data/apps/opt/web-im


pipeline:
  build:
    image: node:7.8
    privileged: true
    commands:
      - npm run build
      - echo 'build success'
    environment:
      - DRONE_REPO_PRIVATE=true
    volumes:
      - /data/apps/opt/web-im/${DRONE_BRANCH}:/data/apps/opt/web-im
    when:
      branch: [dev, wenke, lwz, yiletian, zhongzf, master, release, drone]


