workspace:
  base: /data/apps/opt
  path: web-im


clone:
  git:
    image: plugins/git
    depth: 50
  environment:
    - DOCKER_LAUNCH_DEBUG=true
  debug: true
  commands:
    - echo 'clone success'
  volumes:
    - /data/apps/opt/web-im/${DRONE_BRANCH}:/data/apps/opt/web-im
  when:
    branch: drone

pipeline:
  build:
    image: node:7.8
    privileged: true
    commands:
      - npm run build
      - echo 'build success'
    volumes:
      - /data/apps/opt/web-im/${DRONE_BRANCH}:/data/apps/opt/web-im
    when:
      branch: [dev, wenke, lwz, yiletian, zhongzf, master, release, drone]


